import type {Metadata} from "next";
import {Inter, Nunito} from "next/font/google";
import "@/styles/globals.css";

import Navbar from "@/components/Navbar";
import Footer from "@components/Footer";

const inter = Inter({subsets: ["latin"]});

const nunito = Nunito({subsets: ['latin'], variable: '--font-nunito'});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{ children: React.ReactNode }>) {
  return (
      <html lang="en">
      <body className={`${inter.className} ${nunito.variable}`}>
      <Navbar/>
      <main>{children}</main>
      <Footer/>
      </body>
      </html>
  );
}
